version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/juse2_cicd
    overwrite: yes

permissions:
  - object: /home/ubuntu/juse2_cicd
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: gh_deploy.sh
      timeout: 100
      runas: ubuntu
