name: AWS CI/CD

on:
  push:
    branches:
      - main

env:
  S3_BUCKET_NAME: jusedeploybucket
  CODE_DEPLOY_APPLICATION_NAME: juse-code-deploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: juse-deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Generate Environment Variables File for Production
        run: |
          echo "ABLY_API_KEY=$ABLY_API_KEY" >> .env
          echo "BASE_URL=$BASE_URL" >> .env
          echo "DATABASE_URL=$DATABASE_URL" >> .env
          echo "GOOGLE_ID=$GOOGLE_ID" >> .env
          echo "GOOGLE_SECRET=$GOOGLE_SECRET" >> .env
          echo "MONGODB_URI=$MONGODB_URI" >> .env
          echo "MY_AWS_ACCESS_KEY=$MY_AWS_ACCESS_KEY" >> .env
          echo "MY_AWS_S3_BUCKET=$MY_AWS_S3_BUCKET" >> .env
          echo "MY_AWS_S3_BUCKET_REGION=$MY_AWS_S3_BUCKET_REGION" >> .env
          echo "MY_AWS_SECRET_KEY=$MY_AWS_SECRET_KEY" >> .env
          echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" >> .env
          echo "NEXTAUTH_URL=$NEXTAUTH_URL" >> .env
        env:
          ABLY_API_KEY: ${{ secrets.ABLY_API_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MY_AWS_ACCESS_KEY: ${{ secrets.MY_AWS_ACCESS_KEY }}
          MY_AWS_S3_BUCKET: ${{ secrets.MY_AWS_S3_BUCKET }}
          MY_AWS_S3_BUCKET_REGION: ${{ secrets.MY_AWS_S3_BUCKET_REGION }}
          MY_AWS_SECRET_KEY: ${{ secrets.MY_AWS_SECRET_KEY }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}

      - name: Install dependencies
        run: npm install

      - name: Build next app
        run: npm run build

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip . -x "node_modules/*"
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: |
          aws deploy create-deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip
